version: '3'

services:
    elasticsearch:
        build:
            context: elastic/elasticsearch/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            - ./elastic/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - elk-w2v

    kibana:
        build:
            context: elastic/kibana/
            args:
                ELK_VERSION: $ELK_VERSION
        volumes:
            - ./elastic/kibana/config/:/usr/share/kibana/config:ro
        ports:
            - "5601:5601"
        networks:
            - elk-w2v
        depends_on:
            - elasticsearch

    # w2v:
    #     build: ./elastic/
    #     ports:
    #         - "44800:44800"
    #     environment:
    #         ELASTICSEARCH_BASE_URL: "http://elasticsearch:9200"
    #     depends_on:
    #         - elasticsearch
    #     networks:
    #         - elk-w2v

networks:
    elk-w2v:
        driver: bridge
